using System;

public class GameOption
{
	public enum BoolOption
	{
		DEATH_IS_NOT_PERMANENT,
		AOE_HIGHLIGHTING,
		DISPLAY_UNQUALIFIED_INTERACTIONS,
		DISPLAY_INTERACTION_QUALIFIER,
		DISPLAY_PERSONALITY_REPUTATION_INDICATORS,
		DISPLAY_RELATIVE_DEFENSES,
		DISPLAY_QUEST_OBJECTIVE_TITLES,
		BIG_HEADS,
		HIDE_CIRCLES,
		HIDE_OFFSCREEN_POINTERS,
		ALWAYS_SAVE_OPTIONS,
		LIGATURES,
		DEVELOPER_COMMENTARY,
		COMBAT_TOOLTIPS_UI,
		QUEST_UPDATES_UI,
		COLORBLIND_MODE,
		SOLID_HUD,
		GIBS,
		SCREEN_EDGE_SCROLLING,
		DONT_WARN_STORE_TOO_POOR,
		VSYNC,
		CLIP_CURSOR,
		DONT_RESTRICT_STASH,
		FULLSCREEN,
		SHOW_TUTORIALS,
		DISABLE_PARTY_MOVEMENT_STOP_ON_ENGAGEMENT,
		[Obsolete]
		DISABLE_AUTO_ATTACK,
		PORTRAIT_SHOW_ENDURANCE_VALUE,
		SHOW_NEWS,
		GLOSSARY_EXACT,
		AUTO_LEVEL_COMPANIONS,
		DISABLE_INJURIES,
		SHOW_PORTRAIT_ACTION_ICONS,
		ANALYTICS_MESSAGE_SHOWN,
		ANALYTICS_ENABLED,
		COUNT
	}

	public static bool IsBoolOptionExpert(BoolOption c)
	{
		if (c != 0 && c != BoolOption.AOE_HIGHLIGHTING && c != BoolOption.DISPLAY_UNQUALIFIED_INTERACTIONS && c != BoolOption.DISPLAY_INTERACTION_QUALIFIER && c != BoolOption.DISPLAY_PERSONALITY_REPUTATION_INDICATORS && c != BoolOption.DISPLAY_RELATIVE_DEFENSES && c != BoolOption.DISPLAY_QUEST_OBJECTIVE_TITLES && c != BoolOption.DONT_RESTRICT_STASH && c != BoolOption.COMBAT_TOOLTIPS_UI && c != BoolOption.SHOW_TUTORIALS && c != BoolOption.AUTO_LEVEL_COMPANIONS)
		{
			return c == BoolOption.DISABLE_INJURIES;
		}
		return true;
	}

	public static bool BoolOptionDefault(BoolOption c)
	{
		switch (c)
		{
		default:
			if (c != BoolOption.DONT_RESTRICT_STASH && c != BoolOption.FULLSCREEN && c != BoolOption.SHOW_TUTORIALS && c != BoolOption.PORTRAIT_SHOW_ENDURANCE_VALUE && c != BoolOption.CLIP_CURSOR && c != BoolOption.SHOW_NEWS && c != BoolOption.AUTO_LEVEL_COMPANIONS)
			{
				return c == BoolOption.SHOW_PORTRAIT_ACTION_ICONS;
			}
			break;
		case BoolOption.DEATH_IS_NOT_PERMANENT:
		case BoolOption.AOE_HIGHLIGHTING:
		case BoolOption.DISPLAY_UNQUALIFIED_INTERACTIONS:
		case BoolOption.DISPLAY_INTERACTION_QUALIFIER:
		case BoolOption.DISPLAY_RELATIVE_DEFENSES:
		case BoolOption.DISPLAY_QUEST_OBJECTIVE_TITLES:
		case BoolOption.COMBAT_TOOLTIPS_UI:
		case BoolOption.QUEST_UPDATES_UI:
		case BoolOption.GIBS:
		case BoolOption.SCREEN_EDGE_SCROLLING:
		case BoolOption.VSYNC:
			break;
		}
		return true;
	}
}
